### ISSUE TITLE
Npc using Survivor Crank rifle crashes game

### ISSUE THREAD

**Issue by x7GoSu** [Noctifer-de-Mortem/nocts_cata_mod#126]
Handing a Survivor Crank Rifle to an NPC for use crashes the game.

1.Have a NPC follower. Have a S. Crank rifle in inventory.
2. Give NPC S. Crank rifle to use.
3.Let time pass.

Seems it actually needs some ammo type for an NPC to use without crashing. I gave it "ups_charges": 50, and it work seems to work fine.

**Comment by chaosvolt** [comment]
Odd, though given last I tested UPS weapons tended to make NPCs even more crash-happy...not sure what the best solution would be. We have hand-crank chargers now, though they hilariously inefficient, so hmm...

**Comment by x7GoSu** [comment]
It seems giving them a charge has them shooting it now, but when you talk to them it crashes.

**Comment by x7GoSu** [comment]
Yea this isn't just this mod seems like all ups weapons cause this crash.

**Comment by chaosvolt** [comment]
Yeah, NPCs crashing on conversation was why the highly-complex workaround to let NPCs use UPS weapons got axed, because it started cropping up, never got fixed, and is real damn hard to pinpoint the cause of. For a good while I was basically stuck wondering WHY Cata++ NPCs crashed the game, and only really a dev saying "oh hey, we found this bug with NPCs and UPS guns" by sheer chance made me realize that was causing it...

For now the answer is probably the same as with UPS weapons in general: it's kinda impossible to prevent the player from handing an NPC they'll crash the game with until CDDA itseldf fixed what bugs cause it, the best can can be done is prevent NPCs from spawning with them naturally (and I'm FAIRLY certain the only handmade electronic weapon Cata++ NPcs can spawn with is the battery pistol/rifle, which avoids this via using batteries as magazines, same way the Omnitech weapons use plutonium batteries for the NPC versions).

That said, while the root cause of the bug here is beyond anything Noct or I can do to fix, it might still be worth it to make SOME changes to the hand-crank rifle, simply because hand chargers exist in vanilla. You could probably have a bootleg, unofficial crank rifle simply via using a battery rifle and reloading its mags via hand cranking unloaded batteries.

I could SEE if applying the hand-crank use_action to a gun will charge any magazine loaded inside it, but:
1. 90% chance this will probably just not work.
2. The charge rate is stupidly low, enough that the idea seems rather unlikely to be worth implementing. You'll probably spend all day cranking it for a single shot, and I'm not 100% convinced the charge rate is realistic (having it take all day and have barely made a dent in charging a flashlight or radio battery seems like bullshit to me).

**Comment by chaosvolt** [comment]
And for your amusement, here's basically the entire history of just how awkward getting NPCs to shoot lasers in Cata++ has been:

1. Noct had variant UPS laser guns, and super-soldier NPCs used mundane guns because NPCs suck at figuring out UPS weapons.
2. Noct wanted the NPC super soldiers using the same guns the zombie ones use, so he figured out the idea of adding conversion kits to make them use plutonium cells directly.
3. I saw that the plutonium guns were using ENTIRE plutonium cells for single shots, which is hilariously wasteful. I eventually found out how to rig a way to get NPCs to use UPS weapons, and thus obsoleted the conversion stuff in favor of UPS versions.
4. Then a bug happened where, SOMEHOW, talking to an NPC wielding a UPS weapon crashed the game. At this point we gained plutonium batteries that DON'T act stupid like plutonium cells, so the idea came up to make plutonium-battery-powered the default since that's more NPC-kosher.
5. Noct re-added the ability to optionally convert plut-battery guns into UPS ones, so players aren't stuck struggling to loot plutonium batteries (vanilla has them be craft-only, Cata++ adds itemgroup spawns for them in various places).
6. This briefly broke zombie super soldiers because their ranged attacks expected a UPS weapon but the item IDs pointed to battery-fueled guns, so fixing that became an integral part of some general tweaks and fixes to their behavior.

**Comment by x7GoSu** [comment]
That explains alot lol. Using the hand crank action does seem to work.  It recharges the battery if you activate the rifle. I used the HC light battery and it took around 2 hours to fully charge, it only use 1 charge per shot so I think thats  a pretty good deal.
	"use_action": "HAND_CRANK",
	"ammo": "battery",
	"magazines": [
      [
        "battery",
        [
          "light_battery_cell",
          "light_plus_battery_cell",
          "light_minus_battery_cell",
          "light_disposable_cell",
          "light_minus_disposable_cell"
        ]
      ]
    ]
},

**Comment by chaosvolt** [comment]
Hmm. Will have to take a look then. Granted, I kinda don't like the idea of converting it to hand crank given how inefficient it is, but will look into it. :3

**Comment by chaosvolt** [comment]
So, I've been testing the idea of making the survivor's crank rifle functional, but I've run into a few issues. The first is that you can't force it to have a single fixed magazine. We could have it be basically a crank charger that's also a gun, but as you've noticed the charging rate is rather slow, 25 battery an hour. Being able to swap out batteries for fresh ones scavenged along the way would become the more useful feature, making it essentially an upgraded battery rifle instead.

However, there's an alternative I'm pondering, though I'd like to ask @mlangsdorf if they might be able to ensure my math isn't wildly off:
1. The code states that the charge rate is close to 7 watts, hence why it takes 144 seconds to regain 1 charge of battery (seems to be in kJ, consistent with CBM power assumptions). This will be handy later on, however, there's an assumption that's more important to our math.
2. Charging inflicts 1 fatigue per 1 battery gained. This assumption is vital to sanity-checking the next available alternative.
3. If the crank rifle was instead gaining charges via `ARTC_FATIGUE`, it would deplete a random amount of fatigue (3-9, let's assume a reasonable average of 6) every minute, and adds 1 charge per minute.
4. If we assume that "1 fatigue = 1 kJ" then 1 charge gained by `ARTC_FATIGUE` would be worth 6 kJ, so close to 100 watts. That's one hell of a crank.
5. By this metric, the magazine capacity should be one-sixth of what it would be if it was a mundane battery. For example, if I wanted it to equal 300 battery (allowing the crafting recipe to reasonably utilize a variety of rechargeable light batteries, as they have 50, 100, and 150 capacity) then its actual `clip_size` should be 50.

The only thing left after taking all this into account is balancing the actual gun part, which is complicated by the fact that we don't have a `FIRE_X` feature. Only `FIRE_20`, `FIRE_50`, and `FIRE_100`. Leaving it as-is would use only 6 battery's worth of energy under this logic, which would be either a rather weak laser or an unnaturally efficient one.

The other options would be consuming the equivalents of 120, 300, and 600 kJ which are all quite hefty even if we assume it's an extremely inefficient design. Only `FIRE_50` is neatly compatible with a `clip_size` of 50, which would turn the crank rifle into a superlaser that takes 50 minutes to recharge. `FIRE_20` is a close second, but that leaves you with 10 charges you can't use...

**Comment by mlangsdorf** [comment]
Do whatever you think is best, I'm not helping you any more.
