### ISSUE TITLE
NPC-Related Load Error

### ISSUE THREAD

**Issue by TheRealGunShy** [Noctifer-de-Mortem/nocts_cata_mod#143]
Just got the following load error. I see that there is a closed issue (the most recent, at time of posting) which involves Makeshift Command Centers, but with that issue, the player was actually able to load the world, and crashed later. I'm having an NPC-related issue, according to the file pathing, but somehow it involves  Makeshift Command Centers. Could this possibly inform the issue the other person was having? You can see which mods I have installed.
![Cata++LoadError](https://user-images.githubusercontent.com/44696855/70501532-88975300-1adb-11ea-892c-bcb3a7bc429a.png)

**Comment by chaosvolt** [comment]
That looks like something new, unrelated to https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/131

The cause of that one was back when bayonets and several other gunmods were briefly invalid to attach to a weapon. Since the guns were set to start with specific gunmods attached by default (remnants of a long history of back-and-forth between Noct and I both trying to get NPCs to use laser weapons in a sane manner), the game would just implode as soon as NPCs starting with those invalid weapons were loaded up.

This seems to be something new, likely a change in valid mission start syntax (that's happened a few times already).

**Comment by chaosvolt** [comment]
Er, wait. Update your mod, don't use the launcher. I just double-checked this and the missions are ALREADY set to use `follow` (the intended effect syntax) instead of `join` (the old effect).

This was fixed back in december last year: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/64
