### ISSUE TITLE
Something's up with the color?

### ISSUE THREAD

**Issue by HeartwawyHorror** [Noctifer-de-Mortem/nocts_cata_mod#151]
![image](https://user-images.githubusercontent.com/51540578/71551519-9d1e8b00-29b7-11ea-89ba-2158a09f159d.png)
![image](https://user-images.githubusercontent.com/51540578/71551521-a7d92000-29b7-11ea-8b27-7d5086ebb5c7.png)
![image](https://user-images.githubusercontent.com/51540578/71551526-b1628800-29b7-11ea-83db-81c664b5c50d.png)
Error with loading Cata++ on a new world.

**Comment by ephemeralstoryteller** [comment]
Confirmed with not only Cata++ but also many mods that add map locations (tested with only Secronom and only Arcana, but no issue with only Magiclysm). Also occurs on loading a game with one of these mods starts throwing these same errors too.

That said, this seems to have been brought about by [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/36433) change in build 10085. As far as I can tell, this is cosmetic as far as actually playing goes if you hold down spacebar enough.

**Comment by ephemeralstoryteller** [comment]
Updates:

First screenshot refers to the fact that "light_brown" (as well as dark_red) is not a color that the game recognizes. I'll correct in a PR shortly!

The second is because [this](https://github.com/Noctifer-de-Mortem/nocts_cata_mod/blob/ed6f17fe249d778063dcc0f89203f5b92162699a/Terrain/mapgen_obsolete.json#L1658) bit is making the game fussy. I'll roll that into the above PR too.

The third one will take some more trial and error for my not-coder brain. I'll see what I can do, it'll probably have to be a separate PR if Noctifier-de-Mortem or Chaosvolt don't get there first. ;p

**Comment by ephemeralstoryteller** [comment]
All right, should be working smoothly again, as far as I've tested! Figured it all out, I think ^^

**Comment by chaosvolt** [comment]
That PR hopefully caught all of them, do report here if something was missed.

**Comment by chaosvolt** [comment]
Finally grabbed a build today to test, that covered it just fine.
