### ISSUE TITLE
' Survival Combatives' book doesn't grant skill ever, just tanks stamina for as long as you read it. 

### ISSUE THREAD

**Issue by vlad1492** [Noctifer-de-Mortem/nocts_cata_mod#160]
I was feeling so lucky to find it in a basement. 
My survivor is augmented in both brains and memory, has some unarmed and melee skill too.  This will be awesome! 

... five thirsty days later, still no skill gain or mastery of the technique

**Comment by chaosvolt** [comment]
Hmm. I think I know a possible cause. Update the mod, then try the book again. There was a brief time early on last month where it didn't use melee as its learning skill, which of course was a problem because that's what skill it teaches you, plus what the majority of its post-overhaul features use.

It was fixed by this commit: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/commit/55be76152010ef3eaf7759f0d01bf56c2450081e#diff-d7ee2ff39d6179654b22b2dc27d921f7

Do tell me if it persists though.
