### ISSUE TITLE
Monster_Override.json changing Species entry from ROBOT to ROBOT_MILITARY interferes with Control Laptop?

### ISSUE THREAD

**Issue by DrPariah** [Noctifer-de-Mortem/nocts_cata_mod#188]
It appears that somewhere along the line, Cata++ changed the Species entry of several robot/turret/etc types that spawn around military installations to ROBOT_MILITARY. This causes the Control Laptop item to fail to identify them as valid targets, whereas it still works on creatures that are left at the default ROBOT (Example: it will work on Riot Control turrets and Skitterbots, but not .50 or 5.5.6 Turrets which are included in the Monster_Override). Was this the reason for the change in species entry, to make them unhackable? Or was it related to the Factions, so that automated systems around military installations would have a Friendly/Neutral relationship with the Bio-Weapons without changing it so that _all_ bots would treat them as friendly or neutral?

**Comment by chaosvolt** [comment]
Ah, that's an unexpected consequence, thank you for discovering that. The reason was twofold.

For one, you guessed correctly that it'd allow Bio-Weapon Gamma to get around turrets and military robots, without affecting police robots The second reason was so that only military robots would have an attack trigger added to them via the species entry, so that non-hostile robots won't suddenly become aggressive if you approach them (having miner and eyebots suddenly bum-rush players was not a desired outcome).

Now that I see this causes complications, I realize now that it would be much better to simply add this purely via copy-from species overrides. Attack triggers can be injected into monsters directly. Even better, any aggression above 10 or so is effectively as good as 100 if that creature lacks fear triggers. This means I can simply inject a reduced aggression, say 50, into the already-overridden military robots, then tone down the amount of aggression reduction Gamma receives.

That will cause military robots to act as intended, still leaving police robots fully hostile, without these side effects.

**Comment by DrPariah** [comment]
You're awesome, thank you very much!

**Comment by chaosvolt** [comment]
No worries, thank you for pointing this out.
