### ISSUE TITLE
Bug: Survivor Combative Manual constantly runs out of breath instead of training.

### ISSUE THREAD

**Issue by cthae** [Noctifer-de-Mortem/nocts_cata_mod#197]
Impossible to read/train.

**Comment by chaosvolt** [comment]
Update Cataclysm++, reminder that the launcher does not update mods for you. If you're using current experimental builds, update by downloading the zip using the "clone of download" button on the repo's main page. If you're using 0.D or 0.E stable, releases for stable builds are available in the releases tab on that page.

Most likely cause is the period when Survivor Combatives didn't have a primary skill set, making it default to unarmed, which meant the book teaching the reader melee skill didn't help with learning the style. Commit that fixed it is: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/commit/55be76152010ef3eaf7759f0d01bf56c2450081e#diff-d7ee2ff39d6179654b22b2dc27d921f7

If so, then your version of the mod is very old, that commit dates back to december 2019.

**Comment by cthae** [comment]
I know the launcher doesn't update mods and I updated Cata++ a week ago. Just in case it's a recent fix, I just redownloaded the mod and same stuff happens: https://i.imgur.com/6pUUyp0.png

**Comment by cthae** [comment]
Update: If I read it alone, it actually just increases my melee skill. The bug only occurs when I have my followers around.

**Comment by chaosvolt** [comment]
Ah, that's weird. Given martial arts take a while to learn based on difficulty, and vanilla martial art books don't even count as skill books so they won't ever help raise your chance of learning them the more you read them, in that particular case it seems more a vanilla issue that's not easily dealt it. Making it raise your melee skill is effectively as best as can be done, since that at least makes it more likely that you'll get there eventually compared to vanilla books.

If anything I'd suggest opening an issue in CDDA itself and inquiring about making the study messages better clarify why you're failing to learn the style. Big areas of improvement would be sanity-checking for when readinf with an NPC is somehow affecting it, and better messages to hit at what skill is required and hinting when it's way too low.

**Comment by cthae** [comment]
I learned the style once I got to lvl10. But it's impossible to read while the followers are around.

**Comment by chaosvolt** [comment]
That definitely sounds like a bug of some sort. Just in case, could test with a style book that doesn't raise any skills as well. Either way, lowering its difficulty might be an option (but it is intended to be a fairly advanced style).

**Comment by cthae** [comment]
Normal melee styles books that don't raise skills from vanilla don't cause this bug.

Honestly, I was very surprised by how much melee this requires. I learned it and tried it out with the monomolecular blade. It's ok. But then it's a lot worse than Bionic Combatives. So it doesn't quite make sense for it to require such high melee skill. Looks like it really needs it cuz of disarm, which requires lvl9 melee. Well, disarm is almost completely useless since in 99% of cases we fight against monsters that can't be disarmed.

**Comment by chaosvolt** [comment]
Ah, very odd. Still technically a bug that NPCs would interfere with learning it, but not one you'd normally encounter since it's normal for martial arts books to not teach skills. Lowering the difficulty might be doable, will have to tinker with it when I get the chance,
