### ISSUE TITLE
Game not loading in current CDDA version

### ISSUE THREAD

**Issue by meelock** [Noctifer-de-Mortem/nocts_cata_mod#222]
DEBUG    : Error: Json error: data/mods//nocts_cata_mod/Surv_help/c_spells.json:12:32: missing mandatory member "shape"

    "max_damage": 50,
    "base_casting_time": 200,
    "effect": "recover_energy",
                               ^
    "effect_str": "BIONIC",
    "extra_effects": [ { "id": "c_cbm_rtg_induction_2", "hit_self": true }, { "id": "c_cbm_rtg_induction_3", "hit_self": true } ]
  },

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1146
https://gist.github.com/meelock/1dc117cffbc7ca8bab2d7152e63cd2be

Thanks.

**Comment by chaosvolt** [comment]
Ack, will chuck a fix PR at Noct in a bit.

Cause is the rather questionable idea in https://github.com/CleverRaven/Cataclysm-DDA/pull/44481 to not define a default `shape` for spells, especially since over half the spell effects in the code have no real use for shapes.

You'd think it'd be a good idea, especially since not doing it caused a substantial increase in the amount of JSON work the PR author had to do...
