### ISSUE TITLE
vehicle part generator_electric_enhanced has unknown or incorrectly specified install requirements vehicle_bolt

### ISSUE THREAD

**Issue by linonetwo** [Noctifer-de-Mortem/nocts_cata_mod#242]
This is from experimental 11406, and I am using latest mod from github.

Things are:

surv_station_t
generator_electric
generator_electric_large
generator_electric_enhanced
generator_electric_super

**Comment by linonetwo** [comment]
P.S. do you know why I get this?

> There are too many mandatory overmap specials (77 > 72). Some of them may not be placed.

**Comment by chaosvolt** [comment]
For the unrelated issue, what's your modlist?

**Comment by linonetwo** [comment]
I've just play what's recommended in https://github.com/Kenan2000/BL9#prerequisites :

Secronom, Cata++, Arcana  and BL9

**Comment by chaosvolt** [comment]
Testing this now and I'm getting 73 specials with Arcana, Cata++, and the handful of vanilla mods that add locations.

This is not normal, they've fucked something up here in how overmap specials are parsed. Gonna try to find out what they did here.

**Comment by chaosvolt** [comment]
I'm 90% certain the cause of this is @Venera3 royally fucked up when making the https://github.com/CleverRaven/Cataclysm-DDA/pull/46701 PR, because there are now MORE mandatory specials than there were before, not less.

This is important: *UNIQUE specials are counted as mandatory specials, even if they're not set to appear 100% of the time.*

I can update the crafting requirement thing to fix the primary cause of this issue, I can't do anything to fix the overmap specials thing, I would suggest you use Bright Nights instead: https://github.com/cataclysmbnteam/Cataclysm-BN

**Comment by chaosvolt** [comment]
![image](https://user-images.githubusercontent.com/11582235/105868073-63092980-5fbb-11eb-8077-3817585d9795.png)

```
[
  "dda",
  "Arcana",
  "blazeindustries",
  "No_Fungi",
  "no_npc_food",
  "Cata++",
  "aftershock",
  "magiclysm",
  "crt_expansion",
  "DinoMod"
]
```

There are 5 mandatory specials in Arcana, 5 in Cata++, negative 3 in No Fungal Monsters Mod (it renders the three fungal spawns non-spawning), 0 in Aftershock, 0 in CRIT Expansion, 0 in Dinomod, and 0 in Magiclysm.

That means that **63** of those specials are vanilla, and it would've been 66 if not for NFM.

**Comment by linonetwo** [comment]
Well, this limit looks not nice for mod-players...

**Comment by chaosvolt** [comment]
The fact this limit exists in the first place has always been a huge pain in the ass for modders, yeah. The issue used to be too many specials were set to have occurrences above zero, and they eventually cracked down on that to leave a lot more space open for mods.
