### ISSUE TITLE
Makeshift Commander Center occurrence problem

### ISSUE THREAD

**Issue by vorpal-void** [Noctifer-de-Mortem/nocts_cata_mod#258]
Not really breaking anything aside form immersion, I hope, but overmap specials and mod scenario itself are messing with each other and result in situation where there are several identical makeshift command centers are placed in the world and not really far away from each other (in my current session, one is on 54,74, second is on 115,111).

1. Start quest in makeshift CC to find some badges
2. Go to the specified location and meet there some NPC who's giving the quest to escort them to CC
3. This quest points to the DIFFERENT CC
4. You can't give in first quest in that CC, but you can in the first one if you're drive there or teleport. E
5. It seems like this repetition of occurrence will go on, effectively forcing player to ignore those command centers for the sake of immersion.

Could be related to many mods active at the same time, which clogs the overmap special placement in some form?

**Comment by chaosvolt** [comment]
It's basically a consequence of the fact that "unique" overmap specials aren't truly unique, only that they're limited to one per overmap chunk. Having them direct you to a different location is also likely caused by this, Evy's mission is likely assuming the other command center is the closest one. The best that can be done is double-check that the mission isn't set to ignore already-discovered command centers, which I'll go ahead and look at just in case.

**Comment by CV514** [comment]
Yes, indeed the second CC is closer to a lab I've been pointed to to gather badges; I think I've driven past the second CC some time in-between those activities and it became "visible", so even `must_see` wouldn't do anything in my situation.

It looks like the game could use a means to mark certain map features as uniquely unique to the entire generated world, but that's out of the scope of that issue.

**Comment by chaosvolt** [comment]
I left some feedback on the idea in the issue you linked to this one. For now, not much that can be done about Cata++' use of this.

Arcana at least is able to implement one example of a mostly-truly-unique location by way of a few overmap specials that only generate when you trigger a mission at the refugee center, but it's still hypothetically possible to break them via multiple characters initiating the "find Sofia" mission from a far enough away refugee center. In practice that doesn't matter much because any mission/NPC stuff that involves multiple characters is already INCREDIBLY fragile.

For Cata++ this option doesn't work since both the Bio-Weapon Lab and Makeshift Command Center are both viable entry points to the mission chain, whereas Arcana only has one entry point for the Rural Church subplot.

**Comment by meelock** [comment]
Globally unique tag was recently added. Please use "flags": [ "GLOBALLY_UNIQUE" ] to set it as such. Thanks!

**Comment by meelock** [comment]
Arg, I don't think this should be closed. GLOBALLY_UNIQUE doesn't exist on CBN yet afaik.
