### ISSUE TITLE
Bio-Weapons rebalance?

### ISSUE THREAD

**Issue by RodriguesCIA** [Noctifer-de-Mortem/nocts_cata_mod#360]
Although the Failed Bio-Weapon is entirely playable (albeit somewhat painfully) and can really pull its own weight against most enemies (on default map settings), it is massively outclassed by the others, to the point that the extra 4 points really don't compensate.

An unexpected advantage all the others have is that the Failed Bio-Weapon starts with 6 defect points already, so that's 6 points you can't get from it. By acquiring other defects, your free points can go up to 10 free points. Meanwhile, the other Bioweapons have either -1 or -2 defect points. If you crank all the defects up (which can be challenging to do so smartly, considering many of their positive traits are mutually exclusive to "competitive" defects, but thankfully, most of the harsher defects can be fixed with Nano Serum), you can get between 10 and 11 free points. That means, the best character (at least as far as raw stats go) you can make as a Failed Bio-Weapon, can be as good (and generally MUCH better overall) if you take any other Bio-Weapon.

Meanwhile, unlike all other Bio-Weapons, the Failed starts with A LOT of defective bionics. The combination is not too harmful to gameplay thanks to the good healing and natural armor of the thing (hulks are going to have a field day on you though), but considering the Neural Degeneration + Sentinel Synapse you are likely to get soon in order to fix some other defects, you are unlikely to learn the skills to opperate yourself any time soon. The Bio-Hunter, guaranteed start npc, is smart, but she also got the Synapse, so she will be a slow reader, so she will also take a LONG while to get good enough via books. Finally, in default world settings, your odds of finding other NPCs are very low. Overall, that means you will have to bear these aggravating bionics for a good while.

Finally, the only current objective advantage the Failed Bio-Weapon got over the others is a more spacious positive traits list, at 7, while the others are 13 (figures), 10, and 9. Delta, specifically, though, also got 7, a -2 negative, so you can squeeze 10 more points there and get as much freedom as you would have with Failed. The only price paid is that Delta is a great generalist, while Failed can tank a lot, and will have a much easier time on early game.

My suggestion? Most of the negative traits are filled with Bio-Weapon exclusive defects you can't get in-game or buy in character creation. Reduce their "cost" to 0. This would free up A LOT of points for Failed Bio-Weapon and allow it to be far more competitive in comparison to the others. You will have to endure the goddamn bionics, but at least you will feel like you actually got something for it.

**Comment by chaosvolt** [comment]
> My suggestion? Most of the negative traits are filled with Bio-Weapon exclusive defects you can't get in-game or buy in character creation. Reduce their "cost" to 0. This would free up A LOT of points for Failed Bio-Weapon and allow it to be far more competitive in comparison to the others. You will have to endure the goddamn bionics, but at least you will feel like you actually got something for it.

I've tried to do this with most of the bio-weapon professions in https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/351, which phased out a TON of vanilla traits with point costs, keeping only some things that specifically have effects we can't mimic in JSON.

The profession that's most-strongly affected by this, if I recall, is the Mycus variant since they still have 30+ positive forced trait points due to having a full set of Mycus mutations, meaning they basically can't ever purchase useful traits in chargen.

**Comment by Noctifer-de-Mortem** [comment]
> ...Reduce their "cost" to 0...

Not sure how this affects gameplay, if at all, but when a mutation has a zero cost it becomes a "marker" (profession traits like Bionic Police, MD, etc) and they are outlined in white. This can add confusion when looking at the traits for the player. One way to go about this is to not have Failed-Bio Weapon with the other Bio-Weapon classes and have it's own scenario balanced to it. That still wouldn't solve the 6 points taken issue but it could be a start?

**Comment by chaosvolt** [comment]
Mutations with zero cost are yellow if non-profession, white if profession. either way, the forced points are definitely an annoying complication, but one that's hard to really compensate for. Adjusting the point bonus helps, but the trait points pre-spent will still reduce ability to buy traits, and it remains a problem so long as there are trait effects we want for a profession that can't be done with custom JSON traits like I did in the above PR.

As I mentioned, the fungal bio-weapon is the most extreme example, but the only feasible solution is probably to make them only start with Mycus threshold, and hope that they develop Mycus traits as normal.

**Comment by RodriguesCIA** [comment]
I'd like to comment that I managed to get ALL the bad bionics out in, roughly, 5 days. The girl got SOME decent skills, but it mostly comes down to her high Intelligence due to her mutations. The trivial bionics you can repeatedly try to remove, while the harder ones, a failure will hurt you to roughly half hitpoints in at least one part, most likely multiple. While you heal (with your natural regen and nanobots), go around and supplement your food supply with fruits while you can (might get carnivore, so if you are playing with the risk of unprompted mutations, do not start with any food allergy).

All said and done, you get an interesting mix of melee, tank, and some ranged capability. The tank part is particularly important as, with Unsteady Footwork it will be a while until you dodge anything, but regardless, you are a damn fine abomination.

**Comment by chaosvolt** [comment]
That's a good sign then. I'll still want to see if I can look into the trait point usage of the bio-weapon professions now, and see if there are any more easy cases where forced vanilla traits can be trimmed out, and failing that can take a further look at point costs.

Related, the super soldier professions all tend to have very high point costs, much more than bio-weapons, and also run into some limited instances of forced traits that come with point costs, though since they're all positive traits the effect on min-maxing will likely be lower. Overall this does seem more complex to fix than the other issue involving Evy.

**Comment by chaosvolt** [comment]
So, looking into it, reducing the bio-weapon specific traits from 1 point to 1 points will be the obvious first step. Also could remove the extra Mycus traits from fungal failed bio-weapon, as they get a whopping **20 points** from those. Those changes combined would make the forced trait point expenses the following:


Profession  | Positive Trait Points Pre-Spent | Negative Trait Points Pre-Spent
--- | --- | ---
Failed Bio-Weapon  | +4 | -3
Fungal Failed Bio-Weapon  | +5 | -3
Bio-Weapon Alpha | +9 | 0
Bio-Weapon Beta  | +6 | 0
Bio-Weapon Delta | +4 | -1
Bio-Weapon Gamma | +7 | 0
Super Soldier  | +4 | 0
Super Scout | +4 | 0
Super Bio-Engineer | +4 | 0
Super Juggernaut | +4 | 0

As can be seen, this sharply reduces how bad they eat into available trait points, and is enough to put them all under the default point limit of 12. Alpha and Gamma are still pretty strongly affected, the former largely because Eater of The Dead is so important to their functionality (and it's not easy to fully mimic in JSON), while Gamma's biggest point sink is Fast Learner (which isn't JSONized in BN like reading speed is). Even then, it's a hefty improvement.

Optional things I'd be tempted to do:
1. Reduce profession point costs for failed bio-weapon and fungal failed bio-weapon to zero. They're basically Prototype Cyborgs++, and Prototype Cyborgs have an outright negative point cost (one that's been the subject to debate over in BN, as it's not clear yet whether 2 points is enough given how bad those CBMs are).
2. Reduce profession costs for Alpha, Beta, Delta, and Gamma to 5. 8 points is normally the limit for vanilla super-badass characters, and while the main series Bio-Weapons are various forms of badass, they're also saddled with various drawbacks in terms of mutations, though exactly how useful these drawbacks are as balancing is still kinda yet to be fully determined. Either way I'd be tempted to rank them more on par with combat-ready-but-not-godlike professions, in terms of point cost.
3. Reduce profession costs of Super Soldier, Super Scout, Super Bio-Engineer, and Super Juggernaut to 10. They're overall definite "super-badass" tier professions with very few drawbacks compared to the bio-weapons, but even then 12 may be a bit extreme given all of them are very dependent on keeping both their guns and their CBMs fueled in order to keep things up, and they all generally lean towards less sustainability in terms of power generation compared to the bio-weapons.

Thoughts?

**Comment by RodriguesCIA** [comment]
Unlike the Cyborg, the Failed Bio Weapon, on its intended start, can get rid of all their bad bionics very quick (as I said, 5 days, can expect it as a rough average). The Cyborg starts with the same annoying bad CBMs, a few good ones, and two points, a 15 days headstart, that's about it. How quickly you will get rid of the bad bionics depends on how quickly you can find a NPC to work the Autodoc for you (in vanilla, unlikely unless you pick a start with an NPC, but here, you can just head a Bio Weapons lab). However, one possible advantage over the Failed is that they do not start with genetic chaos, so you will have more control over your mutation, specially important for late game (with body part considerations for things like power armor).

So, many soft, subjective factors to consider. As the Failed Bioweapon is limited to three starts (lab challenge, escaped experiment, and bio weapons lab), the particularities of said starts must be taken in consideration for their final cost. One thing is for certain, the player should get SOMETHING for playing them other than just sheer challenge. The few unique interactions are interesting, but are just a start.

**Comment by chaosvolt** [comment]
Seems like good reason to set aside a point rebalance until after we have a good handle on how balanced it is presently, then. Taking a second look at their bionic setup is also a potential option, i.e. making it more distinct from the Cyborg so the mutation setup isn't their sole upside.

So for now, implementing the above proposal of zero-point traits seems like a good first step I could chuck at Noct sometime tonight.

**Comment by Noctifer-de-Mortem** [comment]
The bio-weapons, profession wise, do need a rehaul similar to the super soldiers; is in custom gear and abilities. Super soldiers are meant to be bio-weapons lite in exchange for them being able to be “mass produced”. Lowering forced point-cost in chargen is something that should be done where possible, but bio-weapons are meant to be taken “as is”, but to make it worth it for the player they need a rehaul. The failed bio-weapon would need a minor one as well, this one is just a matter of balance than anything else.

**Comment by chaosvolt** [comment]
Seems like it'd also tie in well with the above idea of tweaking what bionics the failed bio weapon gets, yeah. For now working on the basic mandatory trait post thing from the issue OP, since it seems the easiest to mess with for now.
