### ISSUE TITLE
Creating New Character with Mod on World

### ISSUE THREAD

**Issue by CptForesight** [Noctifer-de-Mortem/nocts_cata_mod#382]
Evening,

The follow error occurs when a character is attempted to be made _(New Game < Custom Character)_ on a world that has been created with the current DDA file version of the code as a loaded mod.

```
 DEBUG    : Error: Json error: data/mods/nocts_cata_mod_DDA/Monsters/c_monster_override.json:65:23: expected string but got '{'

    "special_when_hit": [ "RETURN_FIRE", 100 ],
    "death_drops": {  },
    "death_function": {
                      ^
                        "corpse_type": "BROKEN" },
    "flags": [ "SEES", "NOHEAD", "ELECTRONIC", "COLDPROOF", "IMMOBILE", "NO_BREATHE" ],
    "anger_triggers": [ "PLAYER_CLOSE", "HURT", "FRIEND_ATTACKED", "FRIEND_DIED" ]


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 865
 VERSION  : 0.F-3

```

**Comment by chaosvolt** [comment]
Are you using stable DDA, experimental DDA, or BN?

**Comment by chaosvolt** [comment]
Oh right yeah, that shows you're using 0.F-3.

Use the right version, reminder that launcher is not good at updating mods, reminder to delete old mod before pasting new one, otherwise your next report is gonna be able leftover files that didn't get cleaned up by a blind copypaste; https://github.com/Noctifer-de-Mortem/nocts_cata_mod/releases
