### ISSUE TITLE
Reload infinite loop

### ISSUE THREAD

**Issue by Jninja1** [Noctifer-de-Mortem/nocts_cata_mod#402]
When a friendly teammate tries to reload an ARC-314 with  no extra batteries they get sent into an infinite loop. This happens even if they have a second weapon.

Expected: When out of ammo, use secondary weapon i.e: knife

Outcome: reload loop

(continued from above) ERROR : src/npcmove.cpp:4668 [void npc::do_reload(const item&)] do_reload failed: no usable ammo for ARC-314 laser rifle
10:55:07.068 ERROR : src/npcmove.cpp:4668 [void npc::do_reload(const item&)] do_reload failed: no usable ammo for ARC-314 laser rifle
[ Previous repeated 6 times ]
10:55:07.155 ERROR : src/npcmove.cpp:4668 [void npc::do_reload(const item&)] do_reload failed: no usable ammo for ARC-314 laser rifle
10:55:07.155 ERROR : src/do_turn.cpp:514 [void {anonymous}::monmove()] NPC Jax entered infinite loop.  Turning on debug mode
10:55:07.570 ERROR : src/npcmove.cpp:4668 [void npc::do_reload(const item&)] do_reload failed: no usable ammo for ARC-314 laser rifle

Comments: The NPC "Jax" is "Sigma"; I renamed him. The loop happens regardless of the name

**Comment by Jninja1** [comment]
> Have you actually tested this with a vanilla NPC that has multiple magazines and a gun that uses magazines though? Or are you saying that giving him a different Omnitech gun doesn't do this?

I tested all of the ranged weapons added from the mod. The weapons that didn't work once depleted were the: AKRO-388, ARC-314, KRX-108, MX-84, and the NEO-33. Once they ran out of ammo completely they got sent into a reload loop. If they had a back up battery, they would reload the gun and use that. If there were no available batteries, a loop would occur. The UPS variants would see them just using the gun as a melee weapon instead of reloading. This happened with the A7 Laser rifle (vanilla) as well. All NPCs were vanilla characters. Normal guns that use bullets would see the NPC reloading or simply using the gun as a melee weapon.

**Comment by chaosvolt** [comment]
Hmm, weird. Will have to see if I can look into it, but that still sounds like a code bug.

**Comment by chaosvolt** [comment]
Bit belatedly, is this in BN or DDA? I've yet to try and mess with this, but thing is this is an AI bug, there's very little chance that any JSON solution is going to fix this, it likely should be opened as an issue in whichever repo this is a problem in.

**Comment by chaosvolt** [comment]
So I just tested this in BN:
![image](https://user-images.githubusercontent.com/11582235/171696431-f9951807-a43b-45b3-ac3f-6ba638c9c515.png)

When Evy runs out she runs up to her targets to smack them with her gun. Then I tested this in DDA:
![image](https://user-images.githubusercontent.com/11582235/171696962-3317bd38-df6d-45a6-abeb-df364cf55cc0.png)

So this is 100% a DDA problem with the NPC AI, good odds of it being in some way tied to nested containers (as with most bugs involving inventory/charges behavior that can be found in DDA but not BN).

You said UPS works, which is good since last I tested they didn't work, so one fix I guess would be to swap back in the E1 variants.
