### ISSUE TITLE
mil-surp weapon packs don't do anything

### ISSUE THREAD

**Issue by aierce** [Noctifer-de-Mortem/nocts_cata_mod#42]
activating them does nothing

**Comment by aierce** [comment]
they are undisassemble too.

**Comment by chaosvolt** [comment]
Sorry for the delay, about to look into this.

**Comment by chaosvolt** [comment]
Okay, I can't reproduce this. Update your mod. I could've sworn I'd updated mil-surp weapon packs to not only use the disassemble use_action, but also use `BLIND_EASY` because you should only need good lighting for that if you're doing an unboxing video. XP

And indeed I did, the fix was back on october 3: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/33

Note that in vanilla, there's still the Home Frontier Starter Pack, which still hasn't been updated to do either, but that's a CDDA issue, not a Cata++ one.
