### ISSUE TITLE
tried to put an item (heavy_atomic_battery_cell) count (1) in a container (UPS_off) that cannot contain it

### ISSUE THREAD

**Issue by waveyl** [Noctifer-de-Mortem/nocts_cata_mod#425]
DEBUG    : tried to put an item (heavy_atomic_battery_cell) count (1) in a container (UPS_off) that cannot contain it: pocket with type （MAGAZINE_WELL）not found

 FUNCTION : put_in
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1494
 VERSION  : 13fbcc2

**Comment by chaosvolt** [comment]
Cause seems to be due to Aftershock overriding the UPS to spawn with internal charges instead of a battery, see discussion in this PR that fixed a slightly different similar problem: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/423

BN also suffers from this but is getting the obvious fix in: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1760

The biggest problem with fixing this is it's essentially a case of "pointless mod edit to vanilla item fucks up any spawns of the item properly loaded, in vanilla or other mods" and there's no actual Cata++-side way to fix something another mod breaks.

The only thing that can be done on Cata++'s end is test whether the vanilla DDA bug that made these UPS spawns required is fixed or not. To elaborate, at some point DDA broke the ability for NPCs to make use of battery-powered ranged weapons, as seen in this issue: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/issues/402 This required switching to giving the NPCs the UPS version of the Omnitech guns instead, as it was discovered that NPCs could finally handle UPS-powered guns without their AI breaking. For reference, the entire reason there are battery-fed versions of these weapons in the first place is because for the longest time NPCs were completely unable to use UPS-powered weapons.

I can test perhaps not specifying a specific battery to use and only specifying charges, which should work the same both with and without Aftershock's override, but I'll need to test and confirm it works as intended in both cases because nested container code is always very fragile and prone to not working yet, as can be seen with a lot of cases where they have to explicitly spawn loaded electronics in a dedicated itemgroup or else it won't work at all.
