### ISSUE TITLE
Don't know if bug or feature - Sentinel (Super soldier) post-threshold blocks other mutations

### ISSUE THREAD

**Issue by Wolf-93** [Noctifer-de-Mortem/nocts_cata_mod#450]
As the title say. I was messing around to see what goodies the nano serum gave, so of course I debugged 100 of them (don't recommend actually injecting all of them). I hit the threshold, and the logical next step was to mix other mutations.

So I spawned either mutagen or serums of every other branch, and tested what would stick. Here's the interesting thing, you get the message that your body reacts, but you don't get any other new mutation (either good or bad). And this is considering the ones not cancelled by the Sentinel mutations.

As a counter-example, cross the threshold with any other type, then keep consuming mutagen or serum from another branch. You freak of nature can still become an even uglier nightmare.

**Comment by chaosvolt** [comment]
Intentional at present: `"allowed_category": [ "SUPER_SOLDIER" ]` It's not super vital for balance, though for super-connected mutation categories it does prevent some potential for weirdness if a mutagen repeatedly rolls something a Sentinel trait chain blocks.

For example, if it tries to give you Fast Healer, Fast Metabolism, or other healing and metabolism traits every time, there's a good chance it could do nothing but repeatedly undo the Sentinel Physicality trait chain (and every mutation dependent on it) instead. In practice it should probably start developing other trait chains eventually, so it probably would be okay to remove this protection from Sentinel, but can probably tinker with how it tends to act without it just in case.

**Comment by Wolf-93** [comment]
Ah, I suspected it was because of that, specially considering how Super Soldier condenses various mutations.

I don't how viable, or how to convey it without breaking the "immersion", but maybe one solution could be to inform the player that once they hit the threshold it's only Super Soldier from then on?

(Btw, you can close the issue if you want)

**Comment by chaosvolt** [comment]
Can go either way yeah, if Noct doesn't get any ideas, when I get home I'll do some testing to see if it's essential to keep that feature or if it can be removed without too many problems. If it stays try to figure out a way to convey to the player that information and present a justification for why.

And sure, no worries.
