### ISSUE TITLE
Stealth Cloak cannot be used (CDDA)

### ISSUE THREAD

**Issue by Acognito** [Noctifer-de-Mortem/nocts_cata_mod#461]
Issue: Found the acs-74 stealth cloak in my normal playthrough and could not get it to work no matter what I tried.  I then opened up a new save and tested the acs-74 stealth cloak as well as the "stealth cloak" and "stealth cloak(on)" found in the debug menu, since looking at the code they seem to be supposed to incur the same effects. 

As one can see in the following screenshots, the character is wearing the stealth cloak and zombies can still see the character normally. I tried activating the cloaks but none of them would work. I tried taking off other clothing, moving around beforehand, and refitting the cloak. Am I using the item incorrectly?

![image](https://user-images.githubusercontent.com/75581231/202892453-0bfe5fbe-8873-4df4-b952-259c17edc5e9.png)
![image](https://user-images.githubusercontent.com/75581231/202892766-16c0cbea-fc40-4537-a13e-7af40fee2cd7.png)
![image](https://user-images.githubusercontent.com/75581231/202892772-394869d5-12a7-44e2-9e84-d80fd850ac7a.png)

**Comment by chaosvolt** [comment]
Oh right, this is likely the same problem as in https://github.com/chaosvolt/cdda-arcana-mod/issues/289, using `{ "passive_effects": [ { "id": "c_stealth_cloak" } ] },` doesn't actually work because DDA's relic code is a busted mess.

**Comment by chaosvolt** [comment]
Yep, just tested the bear form wildshape cloak in Magiclysm, which uses `"relic_data": { "passive_effects": [ { "id": "ench_bearform" } ] },`, in build 2022-10-27-0335:
![image](https://user-images.githubusercontent.com/11582235/202908551-42b33c27-d1ba-42c1-88b7-7298c3524b58.png)

Fucking hell it's been busted for like 2 years at this point, since calling enchantments on items in Bright Nights doesn't work this way either, and BN inherited the same general enchantment code that DDA had circa right before nested containers was merged (not counting a few fixes ported over and some things we fixed ourselves).

**Comment by chaosvolt** [comment]
And there we go. Note that stealth cloaks in old saves might still be busted, debugging in a new one should work. Also note that zombies are bad about pathing into your space based off sound and smell, and the game likes to treat trying to move into your space as an attack, so they can also cause problems for invisible players that way too.
