### ISSUE TITLE
Installing Hydrogen Density Converter mod to plasma weapons throws error

### ISSUE THREAD

**Issue by CShigaki** [Noctifer-de-Mortem/nocts_cata_mod#465]
![image](https://user-images.githubusercontent.com/8991882/211686062-823c1b0e-2e62-485f-a6e5-e36ec77eafaa.png)

To reproduce just get a PPA-5 and install the Hydrogen Density Converter on it.
The above error should pop when installing and pop again when examining the gun, which looks like this after the mod is installed

![image](https://user-images.githubusercontent.com/8991882/211686101-146009d1-9cd1-4c5d-81d7-4ae1d52c86a5.png)
I tried messing around with the JSON but I'm quite new to modding and couldn't find any obvious problem

**Comment by chaosvolt** [comment]
If DDA my guess is yet more nested container charge/ammo issues, I'll see if I can look at it when I get time (been busy today and will be tomorrow too).

**Comment by chaosvolt** [comment]
Finally got the chance to take a look at this in most recent version. Looks like, far as I can tell, the cause of this is because someone rigged pocket data such that you can't simply edit the ammo type of an item unless the offending item already has that ammo type specifed as an option in its pocket. Basically breaking compatability with being able to have third-party mods modify a gun's ammo type outright.

So option to fix, far as I can tell, are either to add overriding edits to every vanilla plasma weapon to tell it to also allow hydrogen gas if modifed (risking problems with any other mod that might touch them, risking  the inevitable issues that will come with tweaking anything involving Korg's buggy nested containers mechanics, and lacking any option to modify plamsa guns added by mods), or just give up on the idea and obsolete the convertor mod entirely in favor of the Omnitech plasma pistol being the only plasma weapon able to use uncompressed hydrogen.
