### ISSUE TITLE
Atomic Battery CBM can't generate bionic power

### ISSUE THREAD

**Issue by waveyl** [Noctifer-de-Mortem/nocts_cata_mod#471]
whether the interrupter is on or off.

**Comment by chaosvolt** [comment]
Hecc. I've been meaning to figure out a fix for that. It was already bad enough that powergen logic is busted such that new perpetural powergen CBMs only work when off rather than on, but evidently they broke it in DDA at some point and I've yet to find out a sensible fix for it. BN currently still has the backwards logic but there's an open PR that'll just outright fix it so that it works correctly when on.

Only thing I can think of is enchantment-based hackery to have it cast a spell that raises CBM power once every X seconds, with the timing matching up with the expected rate of power generation (so 1 kJ every 200 seconds to match 5 watts for example).

The open draft PR seen here (https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/467) will fix things in the BN version at least, but for now DDA version is still completely boned until I can figure out the least-shitty workaround for whatever code they broke.

**Comment by waveyl** [comment]
Maybe like this?
![image](https://user-images.githubusercontent.com/22638873/216799029-bee43ce4-f430-49ff-a3fd-fb4cd68d4e83.png)

**Comment by chaosvolt** [comment]
...eh? What's that from?
