### ISSUE TITLE
[DDA] Solar flashlight expand with charge.

### ISSUE THREAD

**Issue by nemesis688** [Noctifer-de-Mortem/nocts_cata_mod#494]
The Solar flashlight items expand in volume as they charge, going from 500ml to 600ml. Adding "rigid": true, to their pocket data seems to stop this.

Also, when comparing it to the base game flashlight I noticed they use "power_draw": "15 W", instead of "turns_per_charge": 15, . According to the JSON_INFO doc the turns_per_charge is being deprecated so might be worth it swapping them out too.

**Comment by chaosvolt** [comment]
Whoops, sorry for not getting to this sooner.

So about `turns_per_charge` being depreciated, that seems...are you sure? Because last I checked it only worked right for battery-fed items, as it didn't respect whether other fuels have a different energy density.

Given all the stuff like candles, torches, gasoline lanterns, chainsaws etc that don't use batteries, what's their plan for the intended JSON for their active state?

**Comment by nemesis688** [comment]
Sorry for the late reply. For the turns_per_charge the only info I have is what I saw in the doc files. It doesn't really say much only that its deprecated.

"turns_per_charge": 20, // Charges consumed over time, deprecated in favor of power_draw

I guess they could be trying to segment electrical things into their own thing; considering the addition of Watts for the various engines and vehicle parts. Or maybe they are going to go the insane route and try to convert an in game unit of gas/oxyacetylene/mm of candle  into watts. I hope they don't but honestly wouldn't put it past them.

**Comment by chaosvolt** [comment]
Hmm, weird. Looked at it and it's still used by non-electric tools so dunno what to make of that.
