### ISSUE TITLE
Move "take down refrigerator" prompt to "a"ctivate instead of "e"xamine 

### ISSUE THREAD

**Issue by RobertoVGoulart** [Noctifer-de-Mortem/nocts_cata_mod#70]
**Is your feature request related to a problem? Please describe.**
When using "e" to get items from an tile with refrigerator, game always asks if we want to take down it, something that most of the time we don't want to, so it's just an extra step before actually taking food from it, to something that players do very frequently.

**Describe the solution you'd like**
Instead of asking the player whenever we grab items from the tile, turn the refrigerator into an item that's "a"ctivatable

**Describe alternatives you've considered**
Taking the refrigerator down on "g"rab might also be an option, dunno which is easier to code, and both would solve the issue.

**Comment by chaosvolt** [comment]
Sadly I don't think there's a way to set it so activate or grab can do that, but there are two other options that do work.

The first is the real basic idea that was in place prior to the update taking advantage of deployed furniture, adding a construction menu option to unplug the fridge.

The second is to simply override the deconstruction option to turn it into an intact fridge, then ensure that uncrafting its item form is as easy as deconstructing its furniture version is in vanilla.

**Comment by chaosvolt** [comment]
And for @Ilysen if they find this via the link provided in the discourse thread:

It would seem that, due to not overriding vanilla fridges, https://github.com/CleverRaven/Cataclysm-DDA/pull/28386 will have less of a problem with this, but it will still cause a minor degree of issue for players that intend to use the converted fridge for storage.

That said, this seems like a good enough reason to possibly obsolete the fridge changes from Cata++ to avoid them conflicting with each other.
