### ISSUE TITLE
Most Weapons aren't vehicle mountable.

### ISSUE THREAD

**Issue by MisterWytt** [Noctifer-de-Mortem/nocts_cata_mod#72]
Ever since the weapons underwent a name change to Cata++'s own weaponry, like the V27 Pistol to the Neo Pistol and so on, the mod's weaponry cannot be mounted on a turret mount on a vehicle. I'm not sure if this is by design or not, but it would be nice to be able to do this again. The weapons, as far as I can tell, are these:

AKRO-388 laser SMG
NEO-33 laser pistol
ARC-314 laser rifle
MX-84 laser sniper
XARM-37 Pulse Scatter Gun
MK-2 Ionic Cannon

The KRX-108 laser LMG is still mountable, funny enough, but that's it.

**Comment by Noctifer-de-Mortem** [comment]
When it comes to mouting the laser weapons, it’s intentional that only the lmg be mountable. If used with blazemod, it’s possible to make a patch to allow the weapons to be used on turret chassis. Not sure about blazemod itself but in this mod itself turret chassi compatibility was never implemented.

**Comment by chaosvolt** [comment]
The rifle and ionic cannon probably could be changed to allow mounting, but not sure if the other ones make sense. Being able to turn a laser pistol into a turret would look a tad odd.

**Comment by kingofzdom** [comment]
It might LOOK a bit odd but history is filled with odd looking weapons that are very effective. My practical-minded survivor would 99/100 take the ability to fire ammo directly from his vehicle's functionally infinite power supply rather than have to use finite (Or at least less convenient) ammo even if it meant it wouldn't be mobile anymore. It makes more sense than having traditional pistols being mountable.
